services:
  - type: web
    name: trending-stocks-app
    env: node
    rootDir: .
    buildCommand: cd frontend && npm install && npx expo export --platform web && mkdir -p ../backend/public && cp -r dist/* ../backend/public/ && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALPHA_VANTAGE_API_KEY
        value: FQSFVIRBDMJAOHOJ
